### ISSUE TITLE
Project set up 

### ISSUE THREAD

**Issue by Tchilo** [Tchilo/API-based-project#21]
## [Link to project](https://github.com/Tchilo/API-based-project/projects/1)
- add kanban board 
- assign student A and B tasks 
- we are a group of  2

**Comment by Dipeshtwis** [comment]
# Status: Approved ✔️

## Hi @Tchilo &  @VICTOR-CHUKWU, 

Good job on implementing all the requirements. Well Done.

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

**You may close this Pull Request and merge the changes**

  
**Keep being awesome devs and good luck with your next milestone!**
---------

Cheers and Happy coding!👏👏👏
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
_**Dipesh Kumar**_

--------

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project(check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
